add_executable(mesh_demo             mesh_demo.cpp)
add_executable(parametric_demo       parametric_demo.cpp)
add_executable(bezier_patch_demo     bezier_patch_demo.cpp)
add_executable(minimal_surface_demo  minimal_surface_demo.cpp)
add_executable(coons_demo            coons_demo.cpp)
add_executable(point_query_demo      point_query_demo.cpp)
add_executable(compare_with_libigl   compare_with_libigl.cpp)

foreach(tgt mesh_demo parametric_demo bezier_patch_demo minimal_surface_demo coons_demo point_query_demo compare_with_libigl)
  target_link_libraries(${tgt} PRIVATE gwn3d)
endforeach()
